num_of_labs= input("Enter the number of labs completed:")
num_of_quizzes= input("Enter the number of labs completed:")
ass_1= input("Enter grade for assignment 1:")
ass_2= input("Enter grade for assignment 2:")
ass_3= input("Enter grade for assignment 3:")
ass_4= input("Enter grade for assignement 4:")
mid_grade1= input("Enter grade for midterm 1:")
mid_grade2= input("Enter grade for midterm 2:")
final_grade= input("Enter grade for final exam:")
mid_final_prep= input("Enter grade for final exam:")

labs_weight= 0.20 if ( num_of_labs >= 6) else ((num_of_labs/6)*0.20)
quiz_weight= 0.15 if (num_of_quizzes >=6) else ((num_of_quizzes/6)*0.15)
ass_weight= (((ass_1 + ass_2 + ass_3 + ass_4)/4)*0.16)
mid_weight= (((mid_grade1 + mid_grade2)/2)*0.25)
final_weight=(final_grade*0.18)
mid_final_prep_weight=(mid_final_prep*0.06)
End_grade= labs_weight + quiz_weight + mid_weight + final_weight + mid_final_prep_weight + ass_weight
print("Your grade is:" + End_grade)
